<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-06-16 13:19
=======
# Generated by Django 3.2.13 on 2022-06-16 13:08
>>>>>>> myfork

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220616_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
