# Generated by Django 3.2.13 on 2022-06-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0008_alter_box_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='IP')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='storages.storage')),
            ],
        ),
    ]
