# Generated by Django 3.2.13 on 2022-06-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('temperature', models.SmallIntegerField(verbose_name='температура')),
                ('ceiling_height', models.FloatField(verbose_name='Высота в метрах')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='номер')),
                ('width', models.FloatField(verbose_name='ширина')),
                ('length', models.FloatField(verbose_name='длина')),
                ('height', models.FloatField(verbose_name='высота')),
                ('empty', models.BooleanField(verbose_name='свободно')),
                ('rental_price', models.PositiveSmallIntegerField(verbose_name='Стоимость')),
                ('start_current_rent', models.DateField(blank=True, null=True, verbose_name='Начало текущей аренды')),
                ('end_current_rent', models.DateField(blank=True, null=True, verbose_name='Конец текущей аренды')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storages.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'бокс',
                'verbose_name_plural': 'боксы',
            },
        ),
    ]
