# Generated by Django 3.2.13 on 2022-06-15 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RemoveField(
            model_name='box',
            name='empty',
        ),
        migrations.RemoveField(
            model_name='box',
            name='end_current_rent',
        ),
        migrations.RemoveField(
            model_name='box',
            name='start_current_rent',
        ),
        migrations.AddField(
            model_name='box',
            name='floor',
            field=models.SmallIntegerField(default=1, verbose_name='этаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='contacts',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='storage',
            name='description',
            field=models.TextField(default='qwerty', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='feature',
            field=models.CharField(blank=True, max_length=50, verbose_name='особенность'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_delivery', models.BooleanField()),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('status', models.CharField(choices=[('UN', 'Необработан'), ('OTW', 'В пути'), ('D', 'Завершён')], db_index=True, default='UN', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата и время заказа')),
                ('start_current_rent', models.DateField(default=django.utils.timezone.now, verbose_name='Начало текущей аренды')),
                ('end_current_rent', models.DateField(verbose_name='Конец текущей аренды')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='заказы', to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='storages.order', verbose_name='Заказ'),
        ),
    ]
