# Generated by Django 3.2.13 on 2022-06-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_auto_20220615_1612'),
        ('storages', '0002_auto_20220616_0054'),
    ]

    operations = [
    ]
