# Generated by Django 3.2.13 on 2022-06-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_merge_0002_auto_20220615_1612_0002_auto_20220616_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(default='q', max_length=50, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='driving_directions',
            field=models.TextField(blank=True, verbose_name='Схема проезда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='need_delivery',
            field=models.BooleanField(verbose_name='нужна доставка?'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
