# Generated by Django 3.2.13 on 2022-06-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_merge_0002_auto_20220615_1612_0002_auto_20220616_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(default=' ', max_length=50, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='driving_directions',
            field=models.TextField(blank=True, verbose_name='Схема проезда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='need_delivery',
            field=models.BooleanField(verbose_name='нужна доставка?'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='StorageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storages.storage', verbose_name='склад')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
