# Generated by Django 3.2.13 on 2022-06-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0004_auto_20220616_1308'),
        ('storages', '0004_auto_20220616_1719'),
    ]

    operations = [
    ]
