# Generated by Django 3.2.13 on 2022-06-17 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storages', '0005_merge_0004_auto_20220616_1308_0004_auto_20220616_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='заказчик'),
        ),
    ]
