# Generated by Django 3.2.13 on 2022-06-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0006_alter_order_renter'),
        ('storages', '0006_auto_20220618_0905'),
    ]

    operations = [
    ]
